### PR TITLE
Expand on Installation Process

### PR DESCRIPTION
**Pull request by brayniverse**
I've added a bit more information on how to manually download, for those who may not be using bower.

I also added a small bit on what files to include and where to find them.

### CODE REVIEW

**Comment by brayniverse** [comment]
Actually thinking about it, I had a bit of trouble not knowing about json.js as a dependency. I'll reword this update to include that file.

Are there any other amendments you think I should include whilst I'm editing it?

**Comment by brettshollenberger** [comment]
The Lodash dependency, too. This is a good stop gap :)

**Comment by brayniverse** [comment]
Any reason why `bower install ngActiveResource --save-dev` isn't the chosen method instead of manually adding it to bower.json?

**Comment by brettshollenberger** [comment]
Nope :)

**Comment by brayniverse** [comment]
Brilliant, I'll rewrite the PR and send it over then.

**Comment by brettshollenberger** [comment]
Merged in the other

**Pull request closed without merging**
